import { getCalculatorPage } from "@/data/calculator-content";
import { localizedCalculatorSlugs, type Locale, type LocalizedCalculatorSlug } from "@/i18n/config";
import type { LocalizedCalculatorContent } from "@/i18n/dictionaries/types";
import { en as baseEn } from "@/i18n/dictionaries/en";
import { ja as baseJa } from "@/i18n/dictionaries/ja";
import { zh as baseZh } from "@/i18n/dictionaries/zh";

type Copy = {
  name: string; shortName: string; title: string; description: string; keywords: readonly string[];
  formula: string; example: { question: string; answer: string };
  faq: { question: string; answer: string };
  results: readonly string[];
  variants?: Readonly<Record<string, readonly string[]>>;
};
type CopySet = Record<string, Copy>;

const en: CopySet = {
  "change-rate": { name: "Change Rate Calculator", shortName: "Change rate", title: "Change Rate Calculator: Measure an Increase or Decrease", description: "Compare an original value with a new one to find the absolute change and percentage change, including decreases.", keywords: ["change rate calculator", "percentage change", "increase decrease calculator"], formula: "Change = new value − original value. Change rate = (new value − original value) ÷ |original value| × 100.", example: { question: "A value moves from 80 to 100. What changed?", answer: "It increased by 20, which is a 25% increase from the original value." }, faq: { question: "Can the original value be zero?", answer: "The absolute change can be found, but a percentage change from a zero baseline is undefined." }, results: ["Increase amount", "Increase rate"], variants: { decrease: ["Decrease amount", "Decrease rate"] } },
  ratio: { name: "Ratio Calculator", shortName: "Ratio", title: "Ratio Calculator: Simplify A:B and Scale a Proportion", description: "Reduce an A:B ratio and calculate the matching value when you know one side of the proportion.", keywords: ["ratio calculator", "simplify a ratio", "proportion calculator"], formula: "Simplified ratio = A ÷ gcd(A, B) : B ÷ gcd(A, B). Matching B = known A × B ÷ A.", example: { question: "If a 2:3 ratio has A = 10, what is B?", answer: "The ratio simplifies to 2:3, so B is 15 when A is 10." }, faq: { question: "Can a ratio contain decimal values?", answer: "Yes. The calculator scales decimal inputs before simplifying; precision beyond six decimal places is rejected." }, results: ["Simplified A", "Simplified B", "Matching B value"] },
  average: { name: "Average Calculator", shortName: "Average", title: "Average Calculator: Find the Mean, Sum, and Count", description: "Enter a list of numbers to get their total, how many values are included, and the arithmetic mean.", keywords: ["average calculator", "arithmetic mean calculator", "mean of numbers"], formula: "Average = sum of entered values ÷ number of values.", example: { question: "What is the average of 10, 20, and 30?", answer: "Their sum is 60 across 3 values, so the average is 20." }, faq: { question: "How should I separate the numbers?", answer: "Separate each value with a comma or semicolon. Empty entries are ignored." }, results: ["Sum", "Count", "Average"] },
  "weighted-average": { name: "Weighted Average Calculator", shortName: "Weighted average", title: "Weighted Average Calculator: Apply a Weight to Each Value", description: "Pair each value with a weight to calculate an average that reflects the relative importance of each item.", keywords: ["weighted average calculator", "weighted mean", "average with weights"], formula: "Weighted average = Σ(value × weight) ÷ Σ(weights).", example: { question: "What is the weighted average of 80 at weight 2 and 90 at weight 3?", answer: "(80 × 2 + 90 × 3) ÷ 5 = 86." }, faq: { question: "Do the weights need to add up to 100?", answer: "No. Any non-negative weights work as long as their total is greater than zero." }, results: ["Weighted average"] },
  cagr: { name: "CAGR Calculator", shortName: "CAGR", title: "CAGR Calculator: Calculate Compound Annual Growth Rate", description: "Estimate the annualized compound growth rate from an initial value, final value, and number of years.", keywords: ["CAGR calculator", "compound annual growth rate", "annualized growth rate"], formula: "CAGR = (final value ÷ initial value)^(1 ÷ years) − 1.", example: { question: "What is the CAGR from 100 to 121 over 2 years?", answer: "The compound annual growth rate is 10% per year." }, faq: { question: "Is CAGR the same as the average yearly return?", answer: "CAGR is the single constant annual rate that connects the start and end values; it does not describe fluctuations along the way." }, results: ["Compound annual growth rate (CAGR)"] },
  "unit-price": { name: "Unit Price Calculator", shortName: "Unit price", title: "Unit Price Calculator: Compare Cost per Item or Find a Total", description: "Divide a total price by quantity to find the price per item, or multiply unit price by quantity to calculate a total.", keywords: ["unit price calculator", "price per item", "cost per unit calculator"], formula: "Unit price = total price ÷ quantity. Total price = unit price × quantity.", example: { question: "What is the unit price of 12 items costing KRW 18,000?", answer: "Each item costs KRW 1,500." }, faq: { question: "Can I compare package sizes with this tool?", answer: "Yes. Calculate the same unit, such as price per item or per kilogram, for each package." }, results: ["Unit price"], variants: { total: ["Total price"] } },
  "unit-converter": { name: "Unit Converter", shortName: "Unit converter", title: "Unit Converter: Length, Weight, Volume, and Temperature", description: "Convert common metric and imperial units for length, weight, and volume, or convert Celsius and Fahrenheit temperatures.", keywords: ["unit converter", "length converter", "weight conversion", "Celsius Fahrenheit converter"], formula: "Linear conversion = value × source factor ÷ target factor. °F = °C × 9 ÷ 5 + 32.", example: { question: "How many centimeters are in 1 inch?", answer: "1 inch equals 2.54 centimeters." }, faq: { question: "Are temperature conversions simple unit multiplications?", answer: "No. Celsius and Fahrenheit use different zero points, so the converter applies an offset as well as a scale." }, results: ["Converted value"] },
  "simple-interest": { name: "Simple Interest Calculator", shortName: "Simple interest", title: "Simple Interest Calculator: Interest and Ending Balance", description: "Estimate pre-tax simple interest when interest accrues only on the original principal, without compounding.", keywords: ["simple interest calculator", "simple interest formula", "principal interest calculator"], formula: "Interest = principal × annual rate × years. Ending balance = principal + interest.", example: { question: "How much simple interest accrues on KRW 1,000,000 at 5% for 2 years?", answer: "Interest is KRW 100,000, giving an estimated ending balance of KRW 1,100,000 before tax." }, faq: { question: "How is simple interest different from compound interest?", answer: "Simple interest is calculated on the original principal only. Compound interest also earns interest on previously added interest." }, results: ["Simple interest", "Principal plus interest"] },
  "savings-interest": { name: "Savings Interest Calculator", shortName: "Savings interest", title: "Savings Interest Calculator: Monthly Deposits and Maturity Amount", description: "Estimate total deposits, pre-tax interest, and the maturity amount for equal monthly contributions at a stated annual rate.", keywords: ["savings interest calculator", "monthly savings calculator", "savings maturity amount"], formula: "Deposited principal = monthly deposit × months. Estimated interest sums each deposit's remaining earning months at the annual rate.", example: { question: "What if you deposit KRW 100,000 monthly for 12 months at 12%?", answer: "Deposits total KRW 1,200,000. With end-of-month deposits and simple interest, estimated pre-tax interest is KRW 66,000." }, faq: { question: "When is each monthly deposit treated as made?", answer: "This estimate treats deposits as made at the end of each month, so the final deposit earns no interest in the period." }, results: ["Deposited principal", "Estimated pre-tax interest", "Estimated maturity amount"] },
  "deposit-interest": { name: "Deposit Interest Calculator", shortName: "Deposit interest", title: "Deposit Interest Calculator: Estimate Pre-Tax Interest", description: "Estimate simple pre-tax interest and the ending balance for a single deposit using an annual rate and a term in months.", keywords: ["deposit interest calculator", "fixed deposit interest", "pre-tax deposit interest"], formula: "Pre-tax interest = deposit × annual rate × months ÷ 12. Ending balance = deposit + interest.", example: { question: "What is the pre-tax interest on KRW 10,000,000 at 3.6% for 12 months?", answer: "Estimated simple interest is KRW 360,000, for an ending balance of KRW 10,360,000 before tax." }, faq: { question: "How is this different from a monthly savings plan?", answer: "A deposit calculator starts with one lump sum. A savings calculator adds a new contribution each month." }, results: ["Pre-tax interest", "Estimated pre-tax ending balance"] },
  ltv: { name: "LTV Calculator", shortName: "LTV", title: "LTV Calculator: Loan Amount as a Share of Property Value", description: "Calculate the loan-to-value ratio from a property value and loan amount. This is a basic ratio, not an approval or eligibility check.", keywords: ["LTV calculator", "loan to value ratio", "property loan ratio"], formula: "LTV (%) = loan amount ÷ property value × 100.", example: { question: "A KRW 200 million loan on a KRW 500 million property gives what LTV?", answer: "The basic loan-to-value ratio is 40%. No lending rules are applied." }, faq: { question: "Does this result show how much I can borrow?", answer: "No. It only calculates a ratio from your inputs and does not apply any country's lending limits or lender review." }, results: ["LTV"] },
  dti: { name: "DTI Calculator", shortName: "DTI", title: "DTI Calculator: Compare Annual Housing Debt with Income", description: "Calculate a basic debt-to-income ratio using annual income, annual mortgage principal and interest, and annual interest on other debt.", keywords: ["DTI calculator", "debt to income ratio", "annual mortgage debt ratio"], formula: "Basic DTI (%) = (annual mortgage principal and interest + annual interest on other debt) ÷ annual income × 100.", example: { question: "With annual income of KRW 50 million and included annual debt payments of KRW 11 million, what is DTI?", answer: "The basic DTI is 22%. Financial institution rules are not applied." }, faq: { question: "Does this include every debt payment?", answer: "This basic formula includes the mortgage principal and interest plus interest on other debt, as entered. Lender definitions can differ." }, results: ["Basic DTI"] },
  dsr: { name: "DSR Calculator", shortName: "DSR", title: "DSR Calculator: Annual Debt Repayments as a Share of Income", description: "Calculate a basic debt service ratio from annual income and total annual principal-and-interest repayments across loans.", keywords: ["DSR calculator", "debt service ratio", "annual loan repayment ratio"], formula: "Basic DSR (%) = annual repayments on all debt ÷ annual income × 100.", example: { question: "With annual income of KRW 50 million and annual loan repayments of KRW 10 million, what is DSR?", answer: "The basic DSR is 20%. Stress tests and lender-specific rules are excluded." }, faq: { question: "How does this differ from DTI?", answer: "This basic DSR uses total annual principal and interest repayments. The DTI formula here uses housing-loan repayments and interest on other debt." }, results: ["Basic DSR"] },
  margin: { name: "Margin Calculator", shortName: "Margin", title: "Margin Calculator: Gross Profit and Profit Margin", description: "Find gross profit and margin as a share of the selling price. The margin denominator is the sale price, not the cost.", keywords: ["margin calculator", "profit margin calculator", "gross profit margin"], formula: "Gross profit = selling price − cost. Margin (%) = gross profit ÷ selling price × 100.", example: { question: "An item costs KRW 60 and sells for KRW 100. What is the margin?", answer: "Gross profit is KRW 40 and margin is 40% of the selling price." }, faq: { question: "How is margin different from markup?", answer: "Margin divides profit by selling price. Markup divides the same profit by cost." }, results: ["Gross profit", "Profit margin"] },
  markup: { name: "Markup Calculator", shortName: "Markup", title: "Markup Calculator: Markup Rate from Cost and Selling Price", description: "Calculate the markup rate using cost as the base, then compare it with margin, which uses selling price as the base.", keywords: ["markup calculator", "markup percentage", "markup vs margin"], formula: "Markup (%) = (selling price − cost) ÷ cost × 100.", example: { question: "A product costs KRW 60 and sells for KRW 100. What is the markup?", answer: "The markup is 66.67% of cost; the margin is 40% of selling price." }, faq: { question: "Why is markup higher than margin for the same sale?", answer: "The profit is the same, but markup divides by the smaller cost while margin divides by the selling price." }, results: ["Markup amount", "Markup rate"] },
  dday: { name: "D-Day Calculator", shortName: "D-Day", title: "D-Day Calculator: Days Until or Since a Target Date", description: "Choose a reference date and target date to see how many calendar days remain, or how many have passed.", keywords: ["D-Day calculator", "days until date", "countdown date calculator"], formula: "D-day count = target date − reference date, measured in calendar days.", example: { question: "If the target is 10 days after the reference date, what is the result?", answer: "The target is D−10: ten days remain." }, faq: { question: "Is the target day counted as a full remaining day?", answer: "The result is the calendar-day difference between the two dates; the target date itself is D-Day." }, results: ["Days until target"] },
  workdays: { name: "Workday Calculator", shortName: "Workdays", title: "Workday Calculator: Count Weekdays Between Dates", description: "Count weekdays in a date range and choose whether to include the start date and end date separately.", keywords: ["workday calculator", "business days between dates", "weekday counter"], formula: "Workdays = weekdays (Monday through Friday) in the selected inclusive date range.", example: { question: "How many workdays are Monday through Friday in the same week?", answer: "There are 5 weekdays when both endpoints are included." }, faq: { question: "Are public holidays removed?", answer: "No. Saturdays and Sundays are excluded; public holidays are not automatically removed." }, results: ["Weekdays"] },
  bmi: { name: "BMI Calculator", shortName: "BMI", title: "BMI Calculator: Body Mass Index from Height and Weight", description: "Calculate body mass index from height in centimeters and weight in kilograms. The result is general information, not a diagnosis.", keywords: ["BMI calculator", "body mass index calculator", "BMI from height and weight"], formula: "BMI = weight in kilograms ÷ height in meters².", example: { question: "What is the BMI for 70 kg at 175 cm?", answer: "The BMI is about 22.9 kg/m². This number alone does not assess a person's health." }, faq: { question: "Is BMI a medical diagnosis?", answer: "No. It is a screening measure with limitations and should not be treated as an individual diagnosis." }, results: ["BMI"] },
  pace: { name: "Running Pace Calculator", shortName: "Running pace", title: "Running Pace Calculator: Pace per Kilometer and Speed", description: "Use running distance and elapsed time to calculate minutes per kilometer and average speed in kilometers per hour.", keywords: ["running pace calculator", "pace per kilometer", "average running speed"], formula: "Pace (min/km) = total minutes ÷ distance in km. Speed (km/h) = distance ÷ elapsed hours.", example: { question: "What is the pace for 5 km in 27 minutes 30 seconds?", answer: "The pace is 5:30 per kilometer and average speed is 10.91 km/h." }, faq: { question: "What does 5:30 per kilometer mean?", answer: "It means each kilometer takes 5 minutes and 30 seconds at that average pace." }, results: ["Average pace", "Average speed"] },
  "fuel-cost": { name: "Fuel Cost Calculator", shortName: "Fuel cost", title: "Fuel Cost Calculator: Estimate Fuel Needed and Trip Cost", description: "Estimate fuel volume and cost from trip distance, vehicle fuel economy, and fuel price per liter.", keywords: ["fuel cost calculator", "trip fuel cost", "fuel consumption calculator"], formula: "Fuel needed (L) = distance (km) ÷ fuel economy (km/L). Cost = fuel needed × price per liter.", example: { question: "What is the fuel cost for 300 km at 15 km/L and KRW 1,700/L?", answer: "The trip uses about 20 liters and costs about KRW 34,000." }, faq: { question: "Does this predict my exact fuel bill?", answer: "No. It uses the distance, average economy, and price you enter; actual consumption and prices can vary." }, results: ["Fuel needed", "Estimated fuel cost"] },
  "calorie-per-serving": { name: "Calories per Serving Calculator", shortName: "Calories per serving", title: "Calories per Serving Calculator: Estimate a Portion", description: "Divide the total calories of a recipe or package by its total quantity, then estimate calories for the portion you eat.", keywords: ["calories per serving calculator", "portion calorie calculator", "recipe calories per portion"], formula: "Calories in portion = total calories ÷ total quantity × portion quantity.", example: { question: "A recipe has 900 kcal across 6 servings. How many calories are in 1.5 servings?", answer: "The estimate is 225 kcal for 1.5 servings." }, faq: { question: "Can this determine whether a meal is healthy?", answer: "No. It only scales the calorie number you enter and does not provide nutrition or medical advice." }, results: ["Estimated calories per serving"] },
};

const ja: CopySet = {
  "change-rate": { name: "増減率計算", shortName: "増減率", title: "増減率計算｜増加量・減少率を計算", description: "変更前と変更後の値を比べ、増減量と基準値に対する変化率を計算します。", keywords: ["増減率 計算", "変化率 計算", "増加率 減少率"], formula: "変化量 = 変更後 − 変更前。変化率 = (変更後 − 変更前) ÷ |変更前| × 100。", example: { question: "80から100に変わった場合、変化はいくらですか？", answer: "20増加し、変更前の値に対する増加率は25%です。" }, faq: { question: "変更前の値が0でも計算できますか？", answer: "増減量は計算できますが、0を基準とする変化率は定義できません。" }, results: ["増加量", "増加率"], variants: { decrease: ["減少量", "減少率"] } },
  ratio: { name: "比率計算", shortName: "比率", title: "比率計算｜A:Bの簡約と比例値の計算", description: "A:Bの比を簡約し、片方の値を基準に比例するもう一方の値を求めます。", keywords: ["比率 計算", "比を簡単にする", "比例計算"], formula: "簡約した比 = A ÷ 最大公約数 : B ÷ 最大公約数。対応するB = 基準A × B ÷ A。", example: { question: "比が2:3でAが10なら、Bはいくつですか？", answer: "比は2:3のままなので、Bは15です。" }, faq: { question: "小数を含む比も計算できますか？", answer: "はい。小数を内部で拡大して簡約します。小数点以下6桁を超える値は扱えません。" }, results: ["簡約したA", "簡約したB", "対応するBの値"] },
  average: { name: "平均計算", shortName: "平均", title: "平均計算｜合計・個数・算術平均", description: "入力した数値の合計、個数、算術平均をまとめて計算します。", keywords: ["平均 計算", "算術平均", "数値の平均"], formula: "平均 = 入力した数値の合計 ÷ 数値の個数。", example: { question: "10、20、30の平均はいくつですか？", answer: "合計は60、個数は3なので、平均は20です。" }, faq: { question: "数値はどのように区切りますか？", answer: "カンマまたはセミコロンで区切ってください。空欄は計算対象になりません。" }, results: ["合計", "個数", "平均"] },
  "weighted-average": { name: "加重平均計算", shortName: "加重平均", title: "加重平均計算｜値と重みから平均を算出", description: "それぞれの値に重みを設定し、重要度や構成比を反映した加重平均を求めます。", keywords: ["加重平均 計算", "加重平均", "重み付き平均"], formula: "加重平均 = Σ(値 × 重み) ÷ Σ(重み)。", example: { question: "値80に重み2、値90に重み3を付けた平均は？", answer: "(80 × 2 + 90 × 3) ÷ 5 = 86です。" }, faq: { question: "重みの合計を100にする必要がありますか？", answer: "いいえ。重みは0以上で、合計が0より大きければ計算できます。" }, results: ["加重平均"] },
  cagr: { name: "CAGR計算", shortName: "CAGR", title: "CAGR計算｜年平均成長率をかんたん算出", description: "初期値、最終値、期間から複利ベースの年平均成長率を計算します。", keywords: ["CAGR 計算", "年平均成長率", "複合年間成長率"], formula: "CAGR = (最終値 ÷ 初期値)^(1 ÷ 年数) − 1。", example: { question: "100から121へ2年間で増えた場合のCAGRは？", answer: "年平均成長率は年10%です。" }, faq: { question: "CAGRは毎年の平均リターンと同じですか？", answer: "開始値と終了値をつなぐ一定の年率です。途中の値動きを表すものではありません。" }, results: ["年平均成長率 (CAGR)"] },
  "unit-price": { name: "単価計算", shortName: "単価", title: "単価計算｜1個あたりの価格と合計金額", description: "合計金額と数量から単価を計算するか、単価と数量から合計金額を求めます。", keywords: ["単価 計算", "1個あたりの値段", "単位価格 比較"], formula: "単価 = 合計金額 ÷ 数量。合計金額 = 単価 × 数量。", example: { question: "12個で18,000 KRWの商品は1個いくらですか？", answer: "1個あたり1,500 KRWです。" }, faq: { question: "容量の違う商品も比べられますか？", answer: "はい。同じ単位（1個あたり、1kgあたりなど）の価格にそろえて比較できます。" }, results: ["単価"], variants: { total: ["合計金額"] } },
  "unit-converter": { name: "単位変換", shortName: "単位変換", title: "単位変換｜長さ・重さ・容量・温度", description: "長さ、重さ、容量のメートル法・ヤードポンド法の単位と、摂氏・華氏を変換します。", keywords: ["単位 変換", "長さ 単位 換算", "重さ 換算", "摂氏 華氏 変換"], formula: "線形変換 = 値 × 変換元係数 ÷ 変換先係数。華氏 = 摂氏 × 9 ÷ 5 + 32。", example: { question: "1インチは何センチですか？", answer: "1インチは2.54センチです。" }, faq: { question: "温度も単純な倍率で変換しますか？", answer: "いいえ。摂氏と華氏は基準点が異なるため、倍率に加えてオフセットを使います。" }, results: ["変換結果"] },
  "simple-interest": { name: "単利計算", shortName: "単利", title: "単利計算｜元金と期間から利息・元利合計", description: "利息を当初の元金だけに付ける単利方式で、税引前の利息と元利合計を試算します。", keywords: ["単利 計算", "単利 計算式", "元金 利息 計算"], formula: "利息 = 元金 × 年利 × 年数。元利合計 = 元金 + 利息。", example: { question: "元金1,000,000 KRWを年5%で2年間預けると？", answer: "税引前利息は100,000 KRW、元利合計は1,100,000 KRWです。" }, faq: { question: "単利と複利の違いは何ですか？", answer: "単利は当初の元金だけに利息が付きます。複利はそれまでに付いた利息も次の計算に含めます。" }, results: ["単利利息", "元利合計"] },
  "savings-interest": { name: "積立預金利息計算", shortName: "積立利息", title: "積立預金利息計算｜毎月積立と満期額", description: "毎月同額を積み立てる場合の預入元金、税引前の利息、満期額を試算します。", keywords: ["積立 利息 計算", "毎月 積立 計算", "積立 満期額"], formula: "預入元金 = 毎月の積立額 × 月数。利息は各積立分の残り期間に年利を適用して合計します。", example: { question: "毎月100,000 KRWを年12%で12か月積み立てると？", answer: "元金は1,200,000 KRW。月末積立・単利の税引前利息は約66,000 KRWです。" }, faq: { question: "毎月の積立日はいつとして計算しますか？", answer: "各月の月末に積み立てる前提です。最後の積立分には利息が付きません。" }, results: ["積立元金", "税引前の利息見込額", "税引前の満期見込額"] },
  "deposit-interest": { name: "定期預金利息計算", shortName: "預金利息", title: "定期預金利息計算｜税引前利息と満期額", description: "一括で預ける元金、年利、月数から単利ベースの税引前利息と満期額を試算します。", keywords: ["預金 利息 計算", "定期預金 満期", "税引前 利息"], formula: "税引前利息 = 預入額 × 年利 × 月数 ÷ 12。満期額 = 預入額 + 利息。", example: { question: "10,000,000 KRWを年3.6%で12か月預けると？", answer: "税引前利息は360,000 KRW、満期額は10,360,000 KRWです。" }, faq: { question: "積立預金の計算とはどう違いますか？", answer: "こちらは最初に一括で預ける計算です。積立計算では毎月の預入分ごとに利息期間が異なります。" }, results: ["税引前利息", "税引前の満期見込額"] },
  ltv: { name: "LTV計算", shortName: "LTV", title: "LTV計算｜物件価格に対する借入比率", description: "物件価格と借入額からローン・トゥ・バリュー比率を計算します。融資審査や借入可能額の判定は行いません。", keywords: ["LTV 計算", "ローン トゥ バリュー", "不動産 借入 比率"], formula: "LTV (%) = 借入額 ÷ 物件価格 × 100。", example: { question: "5億KRWの物件に2億KRWを借りる場合のLTVは？", answer: "基本計算によるLTVは40%です。融資規制は適用していません。" }, faq: { question: "この結果で借入可能額が分かりますか？", answer: "いいえ。入力値の比率を計算するだけで、各国の融資基準や金融機関の審査は反映しません。" }, results: ["LTV"] },
  dti: { name: "DTI計算", shortName: "DTI", title: "DTI計算｜年収と住宅ローン返済の比率", description: "年収、住宅ローンの年間元利返済額、その他ローンの年間利息から基本DTIを計算します。", keywords: ["DTI 計算", "負債所得比率", "住宅ローン 返済比率"], formula: "基本DTI (%) = (住宅ローンの年間元利返済額 + その他ローンの年間利息) ÷ 年収 × 100。", example: { question: "年収50,000,000 KRW、計算対象の年間支払額11,000,000 KRWなら？", answer: "基本DTIは22%です。金融機関や韓国の規制基準は適用していません。" }, faq: { question: "すべてのローン返済額を入力しますか？", answer: "この計算では住宅ローンの元利返済と他のローンの利息を入力します。実際のDTI定義は審査機関によって異なる場合があります。" }, results: ["基本DTI"] },
  dsr: { name: "DSR計算", shortName: "DSR", title: "DSR計算｜年収に対する年間返済額", description: "年収とすべての借入の年間元利返済額から基本DSRを計算します。ストレス審査や融資判定は含みません。", keywords: ["DSR 計算", "返済負担率", "年間ローン返済 比率"], formula: "基本DSR (%) = すべての借入の年間元利返済額 ÷ 年収 × 100。", example: { question: "年収50,000,000 KRW、年間返済額10,000,000 KRWなら？", answer: "基本DSRは20%です。ストレス金利や金融機関ごとの基準は含みません。" }, faq: { question: "DTIとの違いは何ですか？", answer: "この基本DSRはすべての借入の元利返済額を使います。ここでのDTIは住宅ローン返済とその他借入の利息を使います。" }, results: ["基本DSR"] },
  margin: { name: "利益率計算", shortName: "利益率", title: "利益率計算｜粗利益と売上高基準のマージン", description: "仕入原価と販売価格から粗利益と、販売価格を基準にした利益率を計算します。", keywords: ["利益率 計算", "粗利益 計算", "売上総利益率"], formula: "粗利益 = 販売価格 − 原価。利益率 (%) = 粗利益 ÷ 販売価格 × 100。", example: { question: "原価60、販売価格100の場合の利益率は？", answer: "粗利益は40、販売価格に対する利益率は40%です。" }, faq: { question: "利益率とマークアップ率の違いは？", answer: "利益率は販売価格を分母にし、マークアップ率は原価を分母にします。" }, results: ["粗利益", "利益率"] },
  markup: { name: "マークアップ率計算", shortName: "マークアップ", title: "マークアップ率計算｜原価に対する上乗せ率", description: "原価と販売価格から、原価を基準にしたマークアップ額と上乗せ率を計算します。", keywords: ["マークアップ率 計算", "原価 上乗せ率", "利益率 違い"], formula: "マークアップ率 (%) = (販売価格 − 原価) ÷ 原価 × 100。", example: { question: "原価60、販売価格100の場合のマークアップ率は？", answer: "原価に対するマークアップ率は66.67%です。販売価格基準の利益率は40%です。" }, faq: { question: "なぜ同じ取引のマークアップ率は利益率より高いのですか？", answer: "利益額は同じですが、マークアップは販売価格より小さい原価を分母にするためです。" }, results: ["マークアップ額", "マークアップ率"] },
  dday: { name: "D-Day計算", shortName: "D-Day", title: "D-Day計算｜目標日まで・目標日からの日数", description: "基準日と目標日を選び、目標日までの残り日数または経過日数を確認できます。", keywords: ["D-Day 計算", "目標日までの日数", "日数 カウントダウン"], formula: "D-Dayの日数 = 目標日 − 基準日（暦日）。", example: { question: "基準日の10日後が目標日の場合は？", answer: "目標日までD−10、つまり10日です。" }, faq: { question: "目標日は残り日数に含まれますか？", answer: "2つの日付の暦日差を表示します。目標日当日はD-Dayです。" }, results: ["目標日までの日数"] },
  workdays: { name: "勤務日数計算", shortName: "勤務日数", title: "勤務日数計算｜土日を除いた平日数", description: "期間内の月曜日から金曜日までを数え、開始日と終了日を含めるか個別に指定できます。", keywords: ["勤務日数 計算", "営業日 計算", "土日を除く日数"], formula: "勤務日数 = 選択した期間に含まれる月曜日から金曜日までの日数。", example: { question: "月曜日から金曜日までを両端含めて数えると？", answer: "平日は5日です。" }, faq: { question: "祝日は除外されますか？", answer: "土曜日と日曜日のみ除外します。祝日や臨時休業日は自動で除外しません。" }, results: ["平日数"] },
  bmi: { name: "BMI計算", shortName: "BMI", title: "BMI計算｜身長と体重から体格指数を算出", description: "身長（cm）と体重（kg）からBMIを計算します。結果は参考値で、診断ではありません。", keywords: ["BMI 計算", "体格指数 計算", "身長 体重 BMI"], formula: "BMI = 体重 (kg) ÷ 身長 (m)²。", example: { question: "身長175 cm、体重70 kgの場合のBMIは？", answer: "BMIは約22.9 kg/m²です。この値だけで健康状態を判断することはできません。" }, faq: { question: "BMIは医療診断に使えますか？", answer: "いいえ。BMIには限界があり、個人の診断や医療上の助言の代わりにはなりません。" }, results: ["BMI"] },
  pace: { name: "ランニングペース計算", shortName: "ランニングペース", title: "ランニングペース計算｜1kmあたりの時間と速度", description: "走行距離と時間から、1kmあたりのペースと平均速度を計算します。", keywords: ["ランニング ペース 計算", "1km ペース", "平均走行速度"], formula: "ペース (分/km) = 合計時間 (分) ÷ 距離 (km)。速度 (km/h) = 距離 ÷ 経過時間 (時)。", example: { question: "5 kmを27分30秒で走った場合のペースは？", answer: "1 kmあたり5分30秒、平均速度は約10.91 km/hです。" }, faq: { question: "5:30/kmはどのくらいの速さですか？", answer: "平均して1 kmを5分30秒で走るペースを表します。" }, results: ["平均ペース", "平均速度"] },
  "fuel-cost": { name: "燃料費計算", shortName: "燃料費", title: "燃料費計算｜必要な燃料量とドライブ費用", description: "走行距離、燃費、1リットルあたりの価格から、必要燃料量と費用を試算します。", keywords: ["燃料費 計算", "ドライブ ガソリン代", "燃料消費量 計算"], formula: "必要燃料 (L) = 距離 (km) ÷ 燃費 (km/L)。費用 = 必要燃料 × 1Lあたりの価格。", example: { question: "300 km、燃費15 km/L、1,700 KRW/Lの場合の費用は？", answer: "燃料は約20 L必要で、費用は約34,000 KRWです。" }, faq: { question: "実際の給油額と一致しますか？", answer: "入力した距離・平均燃費・価格による概算です。実際の燃費や価格により変わります。" }, results: ["必要燃料量", "燃料費の目安"] },
  "calorie-per-serving": { name: "1食分カロリー計算", shortName: "1食分カロリー", title: "1食分カロリー計算｜分量に応じたカロリー", description: "料理やパッケージ全体のカロリーと総量から、食べる分量のカロリーを換算します。", keywords: ["1食分 カロリー 計算", "分量別 カロリー", "料理 カロリー 計算"], formula: "食べる分のカロリー = 全体のカロリー ÷ 全体量 × 食べる量。", example: { question: "全体900 kcal、6人分の料理を1.5人分食べると？", answer: "1.5人分の目安は225 kcalです。" }, faq: { question: "この計算で食事の健康度が分かりますか？", answer: "いいえ。入力したカロリーを分量に応じて換算するだけで、栄養・医療上の助言は行いません。" }, results: ["食べる分のカロリー目安"] },
};

const zh: CopySet = {
  "change-rate": { name: "变化率计算器", shortName: "变化率", title: "变化率计算器：计算增加量与减少比例", description: "比较原始值和新值，计算绝对变化量及相对于原始值的百分比变化。", keywords: ["变化率计算", "百分比变化", "增减幅计算器"], formula: "变化量 = 新值 − 原始值。变化率 = (新值 − 原始值) ÷ |原始值| × 100。", example: { question: "数值从 80 变为 100，变化是多少？", answer: "增加了 20，相对于原始值增加 25%。" }, faq: { question: "原始值可以为 0 吗？", answer: "可以计算绝对变化量，但以 0 为基准的百分比变化没有定义。" }, results: ["增加量", "增加率"], variants: { decrease: ["减少量", "减少率"] } },
  ratio: { name: "比例计算器", shortName: "比例", title: "比例计算器：化简 A:B 并计算对应比例值", description: "化简 A:B 比例，并在已知一侧数值时计算另一侧对应的比例值。", keywords: ["比例计算器", "比例化简", "比例式计算"], formula: "化简比例 = A ÷ 最大公约数 : B ÷ 最大公约数。对应的 B = 已知 A × B ÷ A。", example: { question: "比例为 2:3，A 为 10 时 B 是多少？", answer: "比例保持 2:3，因此 B 为 15。" }, faq: { question: "比例可以输入小数吗？", answer: "可以。计算器会先放大再化简；超过小数点后 6 位的输入无法处理。" }, results: ["化简后的 A", "化简后的 B", "对应的 B 值"] },
  average: { name: "平均数计算器", shortName: "平均数", title: "平均数计算器：求总和、数量和算术平均数", description: "输入一组数字，一次计算总和、数字个数和算术平均数。", keywords: ["平均数计算器", "算术平均数", "数字平均值"], formula: "平均数 = 输入数字总和 ÷ 数字个数。", example: { question: "10、20、30 的平均数是多少？", answer: "总和为 60，共 3 个数字，所以平均数是 20。" }, faq: { question: "数字之间如何分隔？", answer: "请用逗号或分号分隔；空白项会被忽略。" }, results: ["总和", "数量", "平均数"] },
  "weighted-average": { name: "加权平均计算器", shortName: "加权平均", title: "加权平均计算器：按数值权重计算平均值", description: "为每个数值输入对应权重，计算反映重要程度或占比的加权平均数。", keywords: ["加权平均计算", "加权平均数", "权重平均值"], formula: "加权平均数 = Σ(数值 × 权重) ÷ Σ(权重)。", example: { question: "数值 80 的权重为 2，数值 90 的权重为 3，平均数是多少？", answer: "(80 × 2 + 90 × 3) ÷ 5 = 86。" }, faq: { question: "权重总和必须等于 100 吗？", answer: "不需要。权重都不能为负，且权重总和必须大于 0。" }, results: ["加权平均数"] },
  cagr: { name: "CAGR 计算器", shortName: "CAGR", title: "CAGR 计算器：计算复合年增长率", description: "根据初始值、最终值和年数，估算复合口径的年均增长率。", keywords: ["CAGR计算", "复合年增长率", "年均增长率计算"], formula: "CAGR = (最终值 ÷ 初始值)^(1 ÷ 年数) − 1。", example: { question: "数值在 2 年内从 100 增至 121，CAGR 是多少？", answer: "复合年增长率为每年 10%。" }, faq: { question: "CAGR 等于每年的平均收益吗？", answer: "它是连接起始值与结束值的恒定年化增速，不体现期间的波动。" }, results: ["复合年增长率 (CAGR)"] },
  "unit-price": { name: "单价计算器", shortName: "单价", title: "单价计算器：计算每件价格或商品总价", description: "用总价除以数量计算每件单价，也可以用单价乘数量得到总价。", keywords: ["单价计算器", "每件价格", "单位价格比较"], formula: "单价 = 总价 ÷ 数量。总价 = 单价 × 数量。", example: { question: "12 件商品共 18,000 KRW，每件多少钱？", answer: "每件单价为 1,500 KRW。" }, faq: { question: "可以比较不同包装规格吗？", answer: "可以。先统一为每件、每公斤等相同单位，再比较价格。" }, results: ["单价"], variants: { total: ["总价"] } },
  "unit-converter": { name: "单位换算器", shortName: "单位换算", title: "单位换算器：长度、重量、容量和温度转换", description: "转换常用公制与英制长度、重量和容量单位，也可换算摄氏度与华氏度。", keywords: ["单位换算器", "长度换算", "重量换算", "摄氏华氏转换"], formula: "线性换算 = 数值 × 原单位系数 ÷ 目标单位系数。华氏度 = 摄氏度 × 9 ÷ 5 + 32。", example: { question: "1 英寸等于多少厘米？", answer: "1 英寸等于 2.54 厘米。" }, faq: { question: "温度也只是乘一个换算系数吗？", answer: "不是。摄氏与华氏的零点不同，因此还需要加上偏移量。" }, results: ["换算结果"] },
  "simple-interest": { name: "单利计算器", shortName: "单利", title: "单利计算器：按本金和期限计算利息", description: "按利息只基于原始本金计算的单利方式，估算税前利息和本息合计。", keywords: ["单利计算器", "单利计算", "本金利息计算"], formula: "利息 = 本金 × 年利率 × 年数。本息合计 = 本金 + 利息。", example: { question: "本金 1,000,000 KRW，年利率 5%，存 2 年，单利是多少？", answer: "税前利息为 100,000 KRW，本息合计为 1,100,000 KRW。" }, faq: { question: "单利和复利有什么区别？", answer: "单利只按原始本金计算；复利会把此前产生的利息也计入后续计算。" }, results: ["单利利息", "本息合计"] },
  "savings-interest": { name: "定期储蓄利息计算器", shortName: "储蓄利息", title: "定期储蓄利息计算器：每月存款与到期金额", description: "估算每月定额存入时的存款本金、税前利息和到期金额。", keywords: ["储蓄利息计算", "每月存款计算", "储蓄到期金额"], formula: "存款本金 = 月存款额 × 月数。利息按各期存款剩余计息月数和年利率逐项合计。", example: { question: "每月存入 100,000 KRW，年利率 12%，持续 12 个月呢？", answer: "存款本金为 1,200,000 KRW。按月末存入和单利估算，税前利息约为 66,000 KRW。" }, faq: { question: "每月存款按月初还是月末计算？", answer: "本计算器按每月月末存入估算，因此最后一次存款不产生利息。" }, results: ["存款本金", "预计税前利息", "预计税前到期金额"] },
  "deposit-interest": { name: "存款利息计算器", shortName: "存款利息", title: "存款利息计算器：估算税前利息和到期金额", description: "输入一次性存款金额、年利率和月数，估算单利税前利息与到期金额。", keywords: ["存款利息计算器", "定期存款到期金额", "税前利息计算"], formula: "税前利息 = 存款金额 × 年利率 × 月数 ÷ 12。到期金额 = 存款金额 + 利息。", example: { question: "存入 10,000,000 KRW，年利率 3.6%，期限 12 个月呢？", answer: "税前利息约为 360,000 KRW，到期金额约为 10,360,000 KRW。" }, faq: { question: "这与每月定额储蓄有什么不同？", answer: "本页按一次性存入计算；定期储蓄会分别计算每月存款的计息时间。" }, results: ["税前利息", "预计税前到期金额"] },
  ltv: { name: "LTV 计算器", shortName: "LTV", title: "LTV 计算器：贷款金额占房产价值的比例", description: "根据房产价格和贷款金额计算贷款价值比。这是基础比例计算，不判断贷款资格或可贷额度。", keywords: ["LTV计算器", "贷款价值比", "房产贷款比例"], formula: "LTV (%) = 贷款金额 ÷ 房产价格 × 100。", example: { question: "房产价值为 500,000,000 KRW，贷款 200,000,000 KRW，LTV 是多少？", answer: "基础 LTV 为 40%；本计算不应用贷款监管规则。" }, faq: { question: "这个结果代表可以贷到的金额吗？", answer: "不代表。这里只计算输入金额的比例，不应用任何国家的贷款限制或金融机构审批规则。" }, results: ["LTV"] },
  dti: { name: "DTI 计算器", shortName: "DTI", title: "DTI 计算器：年收入与住房贷款偿还比例", description: "按年收入、住房贷款年度本息偿还额和其他贷款年度利息，计算基础 DTI 比例。", keywords: ["DTI计算器", "债务收入比", "住房贷款偿还比例"], formula: "基础 DTI (%) = (住房贷款年度本息 + 其他贷款年度利息) ÷ 年收入 × 100。", example: { question: "年收入 50,000,000 KRW，计入的年度偿还额为 11,000,000 KRW，DTI 是多少？", answer: "基础 DTI 为 22%；不应用金融机构或韩国监管规则。" }, faq: { question: "这里会计入所有贷款还款吗？", answer: "此基础公式按输入的住房贷款本息和其他贷款利息计算。实际审查口径可能不同。" }, results: ["基础 DTI"] },
  dsr: { name: "DSR 计算器", shortName: "DSR", title: "DSR 计算器：年度全部还款额占年收入比例", description: "按年收入和所有贷款的年度本息偿还总额，计算基础 DSR；不包含压力测试或贷款资格判断。", keywords: ["DSR计算器", "偿债收入比", "年度贷款偿还比例"], formula: "基础 DSR (%) = 所有贷款年度本息偿还额 ÷ 年收入 × 100。", example: { question: "年收入 50,000,000 KRW，年度贷款还款额 10,000,000 KRW，DSR 是多少？", answer: "基础 DSR 为 20%；不含压力利率或机构规则。" }, faq: { question: "它与 DTI 有什么区别？", answer: "此基础 DSR 使用所有贷款的年度本息；本页 DTI 公式使用住房贷款本息与其他贷款利息。" }, results: ["基础 DSR"] },
  margin: { name: "利润率计算器", shortName: "利润率", title: "利润率计算器：毛利额与销售额利润率", description: "根据成本价和售价计算毛利，并以售价为分母计算利润率。", keywords: ["利润率计算器", "毛利计算", "销售利润率"], formula: "毛利 = 售价 − 成本。利润率 (%) = 毛利 ÷ 售价 × 100。", example: { question: "成本为 60，售价为 100，利润率是多少？", answer: "毛利为 40，按售价计算的利润率为 40%。" }, faq: { question: "利润率和加价率有什么区别？", answer: "利润率以售价为分母；加价率以成本为分母。" }, results: ["毛利额", "利润率"] },
  markup: { name: "加价率计算器", shortName: "加价率", title: "加价率计算器：计算售价相对成本的加价比例", description: "根据成本和售价计算加价额及以成本为基准的加价率，并与利润率区分。", keywords: ["加价率计算器", "成本加价比例", "利润率区别"], formula: "加价率 (%) = (售价 − 成本) ÷ 成本 × 100。", example: { question: "成本为 60，售价为 100，加价率是多少？", answer: "按成本计算的加价率为 66.67%；按售价计算的利润率为 40%。" }, faq: { question: "为什么同一笔交易的加价率会高于利润率？", answer: "利润额相同，但加价率除以较低的成本，利润率则除以售价。" }, results: ["加价额", "加价率"] },
  dday: { name: "倒计日计算器", shortName: "D-Day", title: "D-Day 计算器：计算目标日期剩余或已过天数", description: "选择基准日期和目标日期，查看还剩多少个日历日或已经过去多少天。", keywords: ["D-Day计算", "距离目标日期天数", "日期倒计时"], formula: "D-Day 天数 = 目标日期 − 基准日期（按日历日计算）。", example: { question: "目标日期是基准日之后 10 天，结果是什么？", answer: "显示 D−10，表示还剩 10 天。" }, faq: { question: "目标日会算作剩余的一天吗？", answer: "结果是两个日期之间的日历日差；目标日当天为 D-Day。" }, results: ["距离目标日天数"] },
  workdays: { name: "工作日计算器", shortName: "工作日", title: "工作日计算器：统计日期范围内的工作日", description: "统计日期范围内的周一至周五，并可分别设置是否包含开始日和结束日。", keywords: ["工作日计算器", "日期间工作日", "排除周末计算"], formula: "工作日数 = 所选日期范围内的周一至周五天数。", example: { question: "从周一到周五并包含两端，共几个工作日？", answer: "共 5 个工作日。" }, faq: { question: "法定节假日会自动排除吗？", answer: "不会。计算仅排除周六和周日，不会自动排除节假日或临时休假。" }, results: ["工作日数"] },
  bmi: { name: "BMI 计算器", shortName: "BMI", title: "BMI 计算器：根据身高和体重计算身体质量指数", description: "输入厘米身高和千克体重计算 BMI。结果仅供一般参考，不能作为诊断。", keywords: ["BMI计算器", "身体质量指数计算", "身高体重BMI"], formula: "BMI = 体重 (kg) ÷ 身高 (m)²。", example: { question: "身高 175 cm、体重 70 kg 的 BMI 是多少？", answer: "BMI 约为 22.9 kg/m²。单凭这个数值不能判断个人健康状况。" }, faq: { question: "BMI 可以作为医学诊断吗？", answer: "不可以。BMI 有局限性，不能代替针对个人的诊断或医疗建议。" }, results: ["BMI"] },
  pace: { name: "跑步配速计算器", shortName: "跑步配速", title: "跑步配速计算器：每公里用时与平均速度", description: "根据跑步距离和用时，计算每公里配速以及每小时平均速度。", keywords: ["跑步配速计算", "每公里配速", "平均跑步速度"], formula: "配速 (分钟/km) = 总分钟数 ÷ 距离 (km)。速度 (km/h) = 距离 ÷ 用时 (小时)。", example: { question: "5 km 用时 27 分 30 秒，配速是多少？", answer: "配速为每公里 5 分 30 秒，平均速度约 10.91 km/h。" }, faq: { question: "5:30/km 表示什么？", answer: "表示平均每跑 1 km 需要 5 分 30 秒。" }, results: ["平均配速", "平均速度"] },
  "fuel-cost": { name: "油费计算器", shortName: "油费", title: "油费计算器：估算行程所需燃油与费用", description: "根据行驶距离、平均油耗和每升油价，估算所需燃油量和油费。", keywords: ["油费计算器", "行程油费计算", "燃油消耗计算"], formula: "所需燃油 (L) = 距离 (km) ÷ 油耗 (km/L)。费用 = 所需燃油 × 每升价格。", example: { question: "行驶 300 km，油耗 15 km/L，油价 1,700 KRW/L，费用是多少？", answer: "约需 20 L 燃油，预计费用为 34,000 KRW。" }, faq: { question: "结果会和实际加油金额完全一致吗？", answer: "不会。这是按输入距离、平均油耗和价格估算，实际情况可能不同。" }, results: ["所需燃油量", "预计油费"] },
  "calorie-per-serving": { name: "每份热量计算器", shortName: "每份热量", title: "每份热量计算器：按食用分量估算卡路里", description: "根据整份食物的总热量和总量，换算所食用分量对应的热量。", keywords: ["每份热量计算", "分量卡路里计算器", "食谱热量分摊"], formula: "所食用分量热量 = 总热量 ÷ 总量 × 食用量。", example: { question: "一道食谱共 900 kcal、分为 6 份，吃 1.5 份是多少？", answer: "估算热量为 225 kcal。" }, faq: { question: "这个计算器能判断饮食是否健康吗？", answer: "不能。它只按分量换算输入的热量，不提供营养或医疗建议。" }, results: ["所食用分量的热量估算"] },
};

const fieldLabels: Record<Locale, Record<string, string>> = {
  ko: {},
  en: { old: "Original value", current: "New value", a: "Value A", b: "Value B", known: "Known value for A", numbers: "Numbers to average", values: "Values", weights: "Weights", initial: "Initial value", final: "Final value", years: "Term", mode: "Calculation", total: "Total price", unitPrice: "Price per unit", quantity: "Quantity", category: "Unit category", value: "Value to convert", fromUnit: "From", toUnit: "To", principal: "Principal", rate: "Annual interest rate", monthly: "Monthly deposit", months: "Term", homePrice: "Property value", loan: "Loan amount", income: "Annual income", mortgage: "Annual mortgage principal and interest", otherInterest: "Annual interest on other debt", repayment: "Annual repayments on all debt", cost: "Cost", sale: "Selling price", reference: "Reference date", referenceDate: "Custom reference date", target: "Target date", start: "Start date", end: "End date", includeStart: "Include start date", includeEnd: "Include end date", height: "Height", weight: "Weight", distance: "Distance", hours: "Hours", minutes: "Minutes", efficiency: "Fuel economy", price: "Fuel price", calories: "Total calories", servings: "Total quantity", portion: "Amount eaten" },
  ja: { old: "変更前の値", current: "変更後の値", a: "値 A", b: "値 B", known: "基準となる A の値", numbers: "平均する数値", values: "値の一覧", weights: "重みの一覧", initial: "初期値", final: "最終値", years: "期間", mode: "計算方法", total: "合計金額", unitPrice: "単価", quantity: "数量", category: "単位の種類", value: "変換する値", fromUnit: "変換元", toUnit: "変換先", principal: "元金", rate: "年利", monthly: "毎月の積立額", months: "期間", homePrice: "物件価格", loan: "借入額", income: "年収", mortgage: "住宅ローンの年間元利返済額", otherInterest: "その他ローンの年間利息", repayment: "全ローンの年間返済額", cost: "原価", sale: "販売価格", reference: "基準日", referenceDate: "指定した基準日", target: "目標日", start: "開始日", end: "終了日", includeStart: "開始日を含める", includeEnd: "終了日を含める", height: "身長", weight: "体重", distance: "距離", hours: "時間", minutes: "分", efficiency: "燃費", price: "燃料価格", calories: "全体のカロリー", servings: "全体量", portion: "食べる量" },
  zh: { old: "原始值", current: "新值", a: "数值 A", b: "数值 B", known: "已知的 A 值", numbers: "待计算的数字", values: "数值列表", weights: "权重列表", initial: "初始值", final: "最终值", years: "期限", mode: "计算方式", total: "总价", unitPrice: "单价", quantity: "数量", category: "单位类别", value: "待换算数值", fromUnit: "原单位", toUnit: "目标单位", principal: "本金", rate: "年利率", monthly: "每月存款额", months: "期限", homePrice: "房产价格", loan: "贷款金额", income: "年收入", mortgage: "住房贷款年度本息", otherInterest: "其他贷款年度利息", repayment: "全部贷款年度还款额", cost: "成本", sale: "售价", reference: "基准日期", referenceDate: "自选基准日期", target: "目标日期", start: "开始日期", end: "结束日期", includeStart: "包含开始日期", includeEnd: "包含结束日期", height: "身高", weight: "体重", distance: "距离", hours: "小时", minutes: "分钟", efficiency: "平均油耗", price: "油价", calories: "总热量", servings: "总份量", portion: "食用份量" },
};

const optionLabels: Record<Locale, Record<string, string>> = {
  ko: {},
  en: { "unit-price.mode.unit": "Find unit price", "unit-price.mode.total": "Find total price", "unit-converter.category.length": "Length", "unit-converter.category.weight": "Weight", "unit-converter.category.volume": "Volume", "unit-converter.category.temperature": "Temperature", "dday.reference.today": "Today", "dday.reference.custom": "Choose a date", "workdays.includeStart.true": "Include", "workdays.includeStart.false": "Exclude", "workdays.includeEnd.true": "Include", "workdays.includeEnd.false": "Exclude" },
  ja: { "unit-price.mode.unit": "単価を計算", "unit-price.mode.total": "合計金額を計算", "unit-converter.category.length": "長さ", "unit-converter.category.weight": "重さ", "unit-converter.category.volume": "容量", "unit-converter.category.temperature": "温度", "dday.reference.today": "今日", "dday.reference.custom": "日付を指定", "workdays.includeStart.true": "含める", "workdays.includeStart.false": "含めない", "workdays.includeEnd.true": "含める", "workdays.includeEnd.false": "含めない" },
  zh: { "unit-price.mode.unit": "计算单价", "unit-price.mode.total": "计算总价", "unit-converter.category.length": "长度", "unit-converter.category.weight": "重量", "unit-converter.category.volume": "容量", "unit-converter.category.temperature": "温度", "dday.reference.today": "今天", "dday.reference.custom": "选择日期", "workdays.includeStart.true": "包含", "workdays.includeStart.false": "不包含", "workdays.includeEnd.true": "包含", "workdays.includeEnd.false": "不包含" },
};

const unitNames: Record<Exclude<Locale, "ko">, Record<string, string>> = {
  en: { mm: "Millimeters (mm)", cm: "Centimeters (cm)", m: "Meters (m)", km: "Kilometers (km)", inch: "Inches (in)", ft: "Feet (ft)", yard: "Yards (yd)", mile: "Miles (mi)", mg: "Milligrams (mg)", g: "Grams (g)", kg: "Kilograms (kg)", oz: "Ounces (oz)", lb: "Pounds (lb)", ml: "Milliliters (mL)", l: "Liters (L)", c: "Celsius (°C)", f: "Fahrenheit (°F)" },
  ja: { mm: "ミリメートル (mm)", cm: "センチメートル (cm)", m: "メートル (m)", km: "キロメートル (km)", inch: "インチ (in)", ft: "フィート (ft)", yard: "ヤード (yd)", mile: "マイル (mi)", mg: "ミリグラム (mg)", g: "グラム (g)", kg: "キログラム (kg)", oz: "オンス (oz)", lb: "ポンド (lb)", ml: "ミリリットル (mL)", l: "リットル (L)", c: "摂氏 (°C)", f: "華氏 (°F)" },
  zh: { mm: "毫米 (mm)", cm: "厘米 (cm)", m: "米 (m)", km: "千米 (km)", inch: "英寸 (in)", ft: "英尺 (ft)", yard: "码 (yd)", mile: "英里 (mi)", mg: "毫克 (mg)", g: "克 (g)", kg: "千克 (kg)", oz: "盎司 (oz)", lb: "磅 (lb)", ml: "毫升 (mL)", l: "升 (L)", c: "摄氏度 (°C)", f: "华氏度 (°F)" },
};

const alternateFaq: Record<Exclude<Locale, "ko">, { question: string; answer: string }> = {
  en: { question: "Are my entries stored?", answer: "No. The calculation runs in your browser, and this page does not save the values you enter." },
  ja: { question: "入力した値は保存されますか？", answer: "いいえ。計算はブラウザー内で行われ、入力値をこのページに保存しません。" },
  zh: { question: "输入的数据会被保存吗？", answer: "不会。计算在浏览器中完成，本页面不会保存你输入的数值。" },
};

const genericNotes: Record<Exclude<Locale, "ko">, string> = {
  en: "The result is calculated from the values entered and the formula shown. It is an estimate where product or lender rules may differ.",
  ja: "入力値と表示した計算式による結果です。商品条件や金融機関の基準によって実際の結果と異なる場合があります。",
  zh: "结果根据输入值和页面公式计算。具体产品或贷款机构规则可能会导致实际结果不同。",
};

function sampleInput(slug: string) {
  const page = getCalculatorPage(slug)!;
  return Object.fromEntries(page.fields.map((field) => {
    if (field.type === "select") return [field.name, field.defaultValue ?? field.options?.[0]?.value ?? ""];
    if (field.type === "date") return [field.name, field.name === "start" || field.name === "birth" ? "2026-01-01" : "2026-01-11"];
    if (field.type === "textarea") return [field.name, field.name === "weights" ? "1, 2, 3" : "10, 20, 30"];
    const defaults: Record<string, string> = { rate: "5", years: "2", months: "12", hours: "1", minutes: "30", distance: "5", height: "175", weight: "70", income: "50000000", mortgage: "10000000", otherInterest: "1000000", repayment: "10000000", homePrice: "500000000", loan: "200000000", monthly: "100000", principal: "1000000", price: "1700", efficiency: "15", calories: "900", servings: "6", portion: "1.5", quantity: "12", total: "18000", unitPrice: "1500", cost: "60", sale: "100", initial: "100", final: "121", old: "80", current: "100", a: "2", b: "3", known: "10", value: "10" };
    return [field.name, defaults[field.name] ?? String(Math.max(field.min ?? 1, 1))];
  }));
}

function localizedFields(locale: Exclude<Locale, "ko">, slug: string) {
  const page = getCalculatorPage(slug)!;
  const result: LocalizedCalculatorContent["fields"] = {};
  for (const field of page.fields) {
    const label = fieldLabels[locale][field.name];
    if (!label) throw new Error(`Missing ${locale} label: ${slug}.${field.name}`);
    let unit: string | undefined;
    if (["principal", "monthly", "price", "sale", "amount", "gross", "total", "unitPrice", "cost", "homePrice", "loan", "income", "mortgage", "otherInterest", "repayment"].includes(field.name)) unit = "KRW";
    if (slug === "fuel-cost" && field.name === "price") unit = "KRW/L";
    if (field.name === "rate") unit = "%";
    if (slug === "bmi" && field.name === "height") unit = "cm";
    if (slug === "bmi" && field.name === "weight") unit = "kg";
    if (["distance"].includes(field.name)) unit = "km";
    if (slug === "pace" && field.name === "hours") unit = locale === "en" ? "hours" : locale === "ja" ? "時間" : "小时";
    if (slug === "pace" && field.name === "minutes") unit = locale === "en" ? "min" : locale === "ja" ? "分" : "分钟";
    if (slug === "fuel-cost" && field.name === "efficiency") unit = "km/L";
    if (slug === "calorie-per-serving" && field.name === "calories") unit = "kcal";
    if (slug === "calorie-per-serving" && ["servings", "portion"].includes(field.name)) unit = locale === "en" ? "servings" : locale === "ja" ? "人分" : "份";
    if (slug === "unit-price" && field.name === "quantity") unit = locale === "en" ? "items" : locale === "ja" ? "個" : "件";
    const placeholder = field.name === "numbers" ? (locale === "en" ? "e.g. 10, 20, 30" : locale === "ja" ? "例：10, 20, 30" : "例如：10, 20, 30") : field.name === "values" || field.name === "weights" ? (locale === "en" ? "Separate values with commas" : locale === "ja" ? "カンマで区切って入力" : "请用逗号分隔") : undefined;
    result[field.name] = { label, ...(unit ? { unit } : {}), ...(placeholder ? { placeholder } : {}) };
  }
  return result;
}

function localizedOptions(locale: Exclude<Locale, "ko">, slug: string) {
  const page = getCalculatorPage(slug)!;
  const options: Record<string, Record<string, string>> = {};
  for (const field of page.fields) {
    if (!field.options?.length) continue;
    if (slug === "unit-converter" && (field.name === "fromUnit" || field.name === "toUnit")) continue;
    options[field.name] = {};
    for (const option of field.options) {
      const translated = optionLabels[locale][`${slug}.${field.name}.${option.value}`];
      if (!translated) throw new Error(`Missing ${locale} option label: ${slug}.${field.name}.${option.value}`);
      options[field.name]![option.value] = translated;
    }
  }
  if (slug === "unit-converter") {
    const names = unitNames[locale];
    options.fromUnit = { ...names };
    options.toUnit = { ...names };
  }
  return options;
}

function captureResultLabels(
  slug: LocalizedCalculatorSlug,
  input: Record<string, string>,
  copy: Copy,
): Record<string, string> {
  const page = getCalculatorPage(slug)!;
  const labels: Record<string, string> = {};
  const capture = (values: Record<string, string>, variant?: string) => {
    const outcome = page.calculate(values);
    if (!("results" in outcome)) return;
    outcome.results.forEach((item, index) => {
      labels[item.label] = copy.variants?.[variant ?? ""]?.[index] ?? copy.results[index] ?? copy.results[0] ?? "Result";
      labels[`__result_${index}`] = labels[item.label];
    });
  };
  capture(input);
  for (const field of page.fields) {
    if (field.type !== "select") continue;
    for (const option of field.options ?? []) capture({ ...input, [field.name]: option.value }, option.value);
  }
  if (slug === "change-rate") capture({ ...input, old: "100", current: "80" }, "decrease");
  return labels;
}

function createContent(locale: Exclude<Locale, "ko">, slug: LocalizedCalculatorSlug): LocalizedCalculatorContent {
  const copy = (locale === "en" ? en : locale === "ja" ? ja : zh)[slug];
  if (!copy) throw new Error(`Missing ${locale} content: ${slug}`);
  const source = getCalculatorPage(slug)!;
  const input = sampleInput(slug);
  const labels = captureResultLabels(slug, input, copy);
  const related = source.relatedCalculatorIds.filter((id): id is LocalizedCalculatorSlug => localizedCalculatorSlugs.includes(id as LocalizedCalculatorSlug) && id !== slug);
  const genericHowTo = locale === "en" ? `Enter the values requested above${source.fields.some((field) => field.type === "select") ? " and choose a calculation option" : ""}. ${copy.description} The result is calculated in your browser.`
    : locale === "ja" ? `上の項目に値を入力${source.fields.some((field) => field.type === "select") ? "し、計算方法を選択" : ""}して計算してください。${copy.description} 計算はブラウザー内で行います。`
      : `请填写上方数值${source.fields.some((field) => field.type === "select") ? "并选择计算方式" : ""}。${copy.description} 计算在浏览器中完成。`;
  return {
    name: copy.name, shortName: copy.shortName, title: copy.title, description: copy.description, keywords: copy.keywords,
    howTo: genericHowTo, formula: copy.formula, example: copy.example,
    faqs: [copy.faq, alternateFaq[locale]], related,
    fields: localizedFields(locale, slug), options: localizedOptions(locale, slug), resultLabels: labels,
    validation: locale === "en" ? "Check the values and selections, then try again. The required values must be valid for this calculation." : locale === "ja" ? "入力値と選択内容を確認して、もう一度お試しください。計算に必要な値を正しく入力してください。" : "请检查输入值和选项后重试，并确保所需数值符合计算条件。",
    resultNote: slug === "dti" || slug === "dsr" || slug === "ltv" ? copy.faq.answer : genericNotes[locale],
  };
}

export const additionalCalculatorContent: Record<Exclude<Locale, "ko">, Partial<Record<LocalizedCalculatorSlug, LocalizedCalculatorContent>>> = {
  en: Object.fromEntries(localizedCalculatorSlugs.filter((slug) => !(slug in baseEn.calculators)).map((slug) => [slug, createContent("en", slug)])),
  ja: Object.fromEntries(localizedCalculatorSlugs.filter((slug) => !(slug in baseJa.calculators)).map((slug) => [slug, createContent("ja", slug)])),
  zh: Object.fromEntries(localizedCalculatorSlugs.filter((slug) => !(slug in baseZh.calculators)).map((slug) => [slug, createContent("zh", slug)])),
};
