import type { LocaleDictionary } from "@/i18n/dictionaries/types";

export const ja: LocaleDictionary = {
  locale: "ja", siteName: "今日を暮らすツール", description: "毎日に役立つ計算ツールを、簡単・スピーディーに。",
  nav: { home: "ホーム", calculators: "計算ツール", menu: "計算ツールメニュー", search: "計算ツールを検索", close: "メニューを閉じる", searchEmpty: "一致する計算ツールはありません。", language: "言語", skip: "本文へ移動" },
  categories: { math: "数学・単位変換", finance: "金融", tax: "税金・価格", "date-time": "日付・時間", life: "暮らし", salary: "給与・仕事" },
  calculatorList: { title: "計算ツール", description: "目的に合った計算ツールを選んですぐに使えます。入力値はブラウザー内で計算されます。", breadcrumbHome: "ホーム", breadcrumbCalculators: "計算ツール", count: "件", noResults: "一致する計算ツールはありません。" },
  detail: { home: "ホーム", calculators: "計算ツール", howTo: "使い方", formula: "計算式", example: "計算例", notes: "ご注意", faqs: "よくある質問", related: "関連する計算ツール", result: "計算結果", calculate: "計算する", invalid: "入力内容を確認して、もう一度お試しください。", updated: "最終更新" },
  home: { title: "毎日の計算を、簡単・スピーディーに", description: "暮らしに役立つ計算ツールをわかりやすく提供します。" },
  units: { won: "KRW", number: "数値", year: "年", month: "か月", durationLabel: "期間" },
  categoriesOrder: ["math", "finance", "tax", "date-time", "life"],
  calculators: {
    percentage: { name: "パーセント計算", shortName: "パーセント", title: "パーセント計算｜割合・増減を計算", description: "数値の一定割合、2つの数値の比率、増加率・減少後の値を計算します。", howTo: "計算方法を選び、AとBを入力してください。割合の計算ではAが比較する値、Bが基準値です。", formula: "AのB％ = A × B ÷ 100 · AはBの何％ = A ÷ B × 100 · 増減後の値 = A × (1 ± B ÷ 100)", example: { question: "200の15％はいくつですか？", answer: "200 × 15 ÷ 100 = 30です。" }, faqs: [{ question: "AがBの何％かはどう計算しますか？", answer: "AをBで割り、100を掛けます。基準値Bが0の場合は計算できません。" }, { question: "15％増やしてから15％減らすと元に戻りますか？", answer: "戻りません。増加後の値を基準に減少率を適用するため、元の値より少し小さくなります。" }], related: ["discount", "loan-interest", "compound-interest"], fields: { mode: { label: "計算方法" }, a: { label: "値 A" }, b: { label: "値 B" } }, options: { mode: { of: "AのB％", "what-percent": "AはBの何％", increase: "AをB％増加", decrease: "AをB％減少" } }, resultLabels: { "A의 B%": "計算結果", "A는 B의": "AはBの割合", "증가 후 값": "増加後の値", "감소 후 값": "減少後の値" }, validation: "選択した計算方法に合った数値を入力してください。", resultNote: "選択した割合の計算式による結果です。" },
    discount: { name: "割引計算", shortName: "割引", title: "割引計算｜割引額と割引後の価格", description: "定価と割引率から割引額・販売価格を計算するか、定価と販売価格から実際の割引率を求めます。", howTo: "割引率から計算するか、販売価格から割引率を逆算するかを選び、必要な金額を入力してください。割引額は1ウォン単位で四捨五入します。", formula: "割引額 = 定価 × 割引率 ÷ 100 · 販売価格 = 定価 − 割引額 · 割引率 = (定価 − 販売価格) ÷ 定価 × 100", example: { question: "50,000ウォンの商品が20％引きの場合は？", answer: "割引額は10,000ウォン、販売価格は40,000ウォンです。" }, faqs: [{ question: "販売価格から割引率を計算できますか？", answer: "はい。定価と販売価格から逆算する方法を選んでください。" }, { question: "販売価格が定価より高くても計算できますか？", answer: "割引ではなく値上げにあたるため、この計算では扱いません。" }], related: ["percentage", "vat", "loan-interest"], fields: { mode: { label: "計算方法" }, price: { label: "定価", unit: "KRW" }, rate: { label: "割引率", unit: "%" }, sale: { label: "販売価格", unit: "KRW" } }, options: { mode: { rate: "定価と割引率から計算", actual: "定価と販売価格から逆算" } }, resultLabels: { "할인 금액": "割引額", "최종 가격": "販売価格", "실제 할인율": "実際の割引率" }, validation: "定価は0以上、割引率は0～100％で入力してください。逆算では販売価格を定価以下にしてください。", resultNote: "割引額はウォン単位に四捨五入しています。" },
    "loan-interest": { name: "ローン返済計算", shortName: "ローン", title: "ローン返済計算｜月々の返済額と利息", description: "元利均等・元金均等・満期一括返済の初回返済額、利息合計、返済総額を試算します。", howTo: "借入額、年利、返済期間を入力し、返済方式を選択してください。期間は年または月で入力できます。", formula: "元利均等 = P × r ÷ (1 − (1+r)^−n) · 元金均等 = 元金 ÷ 回数 + 残高に対する利息 · 満期一括 = 毎月利息を払い、満期に元金を返済", example: { question: "12,000,000ウォンを年利0％、12か月で返済すると？", answer: "元利均等返済では毎月約1,000,000ウォン、利息は0ウォンです。" }, faqs: [{ question: "元利均等と元金均等の違いは？", answer: "元利均等は毎月の返済額がほぼ一定です。元金均等は元金を一定額ずつ返すため、初回の返済額が大きくなります。" }, { question: "満期一括返済とは？", answer: "期間中は利息を支払い、満期日に元金をまとめて返済する方式です。" }], related: ["compound-interest", "percentage", "discount"], fields: { principal: { label: "借入額", unit: "KRW" }, rate: { label: "年利", unit: "%" }, months: { label: "返済期間" }, method: { label: "返済方式" } }, options: { method: { "equal-payment": "元利均等", "equal-principal": "元金均等", bullet: "満期一括返済" } }, resultLabels: { "첫 회차 납입액": "初回返済額", "월 이자 납입액": "毎月の利息", "만기 상환액": "満期返済額", "총 이자": "利息合計", "총 상환액": "返済総額" }, validation: "借入額は0より大きく、年利は0以上、期間は1～1,200か月の整数で入力してください。", resultNote: "概算です。毎月の利息をウォン単位で丸めており、金融機関の返済日・手数料・金利変更は反映しません。" },
    "compound-interest": { name: "複利計算", shortName: "複利", title: "複利計算｜複利頻度別の元利合計", description: "元金、年利、期間、複利の頻度から満期額と利息を試算します。", howTo: "元金、年利、運用期間、利息を元金に組み入れる頻度を入力してください。期間は年・月を選べます。", formula: "満期額 = 元金 × (1 + 年利 ÷ 複利回数)^(複利回数 × 年数)", example: { question: "1,000,000ウォンを年利12％、月複利で1年間運用すると？", answer: "税引前の満期額は約1,126,825ウォン、利息は約126,825ウォンです。" }, faqs: [{ question: "複利の頻度で結果は変わりますか？", answer: "同じ年利なら、利息をより頻繁に元金へ組み入れるほど試算額は大きくなります。" }, { question: "税引後の金額ですか？", answer: "いいえ。税金、手数料、追加積立、商品ごとの条件は含みません。" }], related: ["loan-interest", "percentage", "discount"], fields: { principal: { label: "元金", unit: "KRW" }, rate: { label: "年利", unit: "%" }, years: { label: "期間" }, frequency: { label: "複利の頻度" } }, options: { frequency: { "1": "年1回", "2": "年2回", "4": "年4回", "12": "年12回（月複利）", "365": "年365回（日複利）" } }, resultLabels: { "최종 금액": "満期額", "총 이자": "利息合計" }, validation: "元金・年利・期間は0以上で入力し、複利の頻度を選んでください。", resultNote: "理論上の税引前試算です。税金、手数料、変動金利、追加積立は含みません。" },
    vat: { name: "付加価値税計算", shortName: "VAT", title: "付加価値税計算｜税抜・税込金額", description: "税抜金額から税額と合計を計算するか、税込金額から税抜金額と税額を逆算します。", howTo: "税抜金額に税を加えるか、税込合計から逆算するかを選びます。一般的な10％で計算し、ウォン単位に丸めます。", formula: "税額 = 税抜金額 × 10％ · 合計 = 税抜金額 + 税額 · 税込金額から税抜 = 合計 ÷ 1.1", example: { question: "税抜10,000ウォンの税額は？", answer: "税額は1,000ウォン、税込合計は11,000ウォンです。" }, faqs: [{ question: "税込金額から税額を求めるには？", answer: "合計を1.1で割って税抜額を求め、合計との差を税額とします。" }, { question: "すべての取引に10％が適用されますか？", answer: "免税や軽減などの扱いがあるため、個別の税務判断には利用できません。" }], related: ["discount", "percentage", "loan-interest"], fields: { mode: { label: "計算方法" }, amount: { label: "税抜金額", unit: "KRW" }, gross: { label: "税込合計", unit: "KRW" } }, options: { mode: { supply: "税抜金額から計算", gross: "税込合計から逆算" } }, resultLabels: { "공급가액": "税抜金額", "부가세": "税額", "합계 금액": "税込合計", "포함된 부가세": "含まれる税額" }, validation: "0以上の金額を入力し、計算方法を選んでください。", resultNote: "一般的な10％の計算です。取引固有の税務条件は反映しません。" },
    "date-difference": { name: "日付の差計算", shortName: "日付差", title: "日付の差計算｜2つの日付の日数", description: "開始日と終了日の経過日数を計算し、両端の日付を含めた日数も確認できます。", howTo: "開始日、終了日、端の日付を含めるかを選択してください。経過日数と指定した条件の日数を別々に表示します。", formula: "経過日数 = 終了日 − 開始日 · 含む日数 = 期間内の日数 + 選択した端の日数", example: { question: "1月1日から1月3日までは何日ですか？", answer: "経過日数は2日、両端を含めると3日です。" }, faqs: [{ question: "開始日と終了日は自動的に含まれますか？", answer: "経過日数とは別に、選択した端の日付条件で日数を表示します。" }, { question: "終了日を開始日より前にできますか？", answer: "終了日は開始日と同じ日、または後の日付を選んでください。" }], related: ["age", "percentage", "discount"], fields: { start: { label: "開始日" }, end: { label: "終了日" }, include: { label: "端の日付を含む" } }, options: { include: { none: "両端を含めない", start: "開始日を含む", end: "終了日を含む", both: "両端を含む" } }, resultLabels: { "날짜 차이": "経過日数", "선택한 포함 기준 일수": "指定条件の日数" }, validation: "有効な日付を選び、終了日が開始日より前にならないようにしてください。", resultNote: "時刻や夏時間ではなく、暦日単位で数えます。" },
    age: { name: "年齢計算", shortName: "年齢", title: "年齢計算｜指定日時点の満年齢", description: "生年月日と基準日から、基準日時点の満年齢を計算します。", howTo: "生年月日と年齢を確認したい日を選択してください。韓国式の数え年ではなく、誕生日を迎えた年数を表示します。", formula: "満年齢 = 基準年 − 生年 − (基準日までに今年の誕生日を迎えていなければ1)", example: { question: "2000年12月31日生まれの2026年12月30日時点の年齢は？", answer: "2026年の誕生日の前日なので満25歳です。" }, faqs: [{ question: "過去の日付時点の年齢も計算できますか？", answer: "はい。基準日は生年月日と同じ日、またはそれ以降を選んでください。" }, { question: "2月29日生まれは平年にどう扱いますか？", answer: "この計算では平年の3月1日を誕生日として扱います。" }], related: ["date-difference", "percentage", "discount"], fields: { birth: { label: "生年月日" }, reference: { label: "基準日" } }, options: {}, resultLabels: { "만 나이": "満年齢" }, validation: "有効な日付を選んでください。基準日は生年月日と同じ日か、それ以降にしてください。", resultNote: "選択した基準日時点の満年齢です。" },
    area: { name: "平方メートル・坪変換", shortName: "面積", title: "面積変換｜平方メートルと韓国の坪", description: "面積を平方メートル（㎡）と韓国で使われる面積単位「坪」の間で変換します。", howTo: "変換方向と面積を入力してください。小数点以下2桁まで表示し、不要な末尾の0は省きます。", formula: "坪 = 平方メートル ÷ (400 ÷ 121) · 平方メートル = 坪 × (400 ÷ 121) · 1坪 ≈ 3.305785㎡", example: { question: "約33.06㎡は何坪ですか？", answer: "約10坪です。" }, faqs: [{ question: "1坪は何平方メートルですか？", answer: "計算では1坪を400/121㎡、約3.305785㎡として扱います。" }, { question: "変換結果が丸められるのはなぜですか？", answer: "換算係数が有限小数ではないため、表示桁数に合わせて丸めます。" }], related: ["date-difference", "percentage", "vat"], fields: { mode: { label: "変換方向" }, value: { label: "面積" } }, options: { mode: { "sqm-to-pyeong": "平方メートルから坪", "pyeong-to-sqm": "坪から平方メートル" } }, resultLabels: { "평": "坪", "제곱미터": "平方メートル" }, validation: "0以上の面積を入力し、変換方向を選んでください。", resultNote: "坪は慣用単位です。韓国の公式な不動産書類では平方メートルをご確認ください。" },
  },
};
