import type { LocaleDictionary } from "@/i18n/dictionaries/types";
import { calculatorCategoryOrder } from "@/data/calculators/categories";

export const zh: LocaleDictionary = {
  locale: "zh", siteName: "今日生活工具", description: "简单、快捷地使用日常计算器和生活工具。",
  nav: { home: "首页", calculators: "计算器", menu: "计算器菜单", search: "搜索计算器", close: "关闭菜单", searchEmpty: "没有找到匹配的计算器。", language: "语言", skip: "跳转到正文" },
  categories: { math: "数学与单位换算", finance: "金融", tax: "税费与价格", "date-time": "日期与时间", life: "生活", salary: "薪资与工作" },
  calculatorList: { title: "计算器与生活工具", description: "选择所需的计算器即可使用。输入内容仅在浏览器中计算。", breadcrumbHome: "首页", breadcrumbCalculators: "计算器", count: "项", noResults: "没有找到匹配的计算器。" },
  detail: { home: "首页", calculators: "计算器", howTo: "使用方法", formula: "计算公式", example: "计算示例", notes: "注意事项", faqs: "常见问题", related: "相关计算器", result: "计算结果", calculate: "开始计算", invalid: "请检查输入内容后重试。", updated: "最后更新" },
  home: { title: "让日常计算更简单快捷", description: "提供清晰易用的日常计算器和生活工具。" },
  units: { won: "KRW", number: "数值", year: "年", month: "个月", durationLabel: "期限" },
  categoriesOrder: calculatorCategoryOrder,
  calculators: {
    percentage: { name: "百分比计算器", shortName: "百分比", title: "百分比计算器：比例、增长与减少", description: "计算数值的百分之几、两个数值的比例，以及按百分比增长或减少后的数值。", howTo: "选择计算方式后输入A和B。计算比例时，A为比较值，B为基准值。", formula: "A的B% = A × B ÷ 100 · A占B的百分比 = A ÷ B × 100 · 增减后数值 = A × (1 ± B ÷ 100)", example: { question: "200的15%是多少？", answer: "200 × 15 ÷ 100 = 30。" }, faqs: [{ question: "如何计算A占B的百分之几？", answer: "用A除以B再乘以100。B为0时无法计算比例。" }, { question: "先增加15%再减少15%会回到原数吗？", answer: "不会。减少比例基于增加后的数值计算，因此结果会略低于原数。" }], related: ["discount", "loan-interest", "compound-interest"], fields: { mode: { label: "计算方式" }, a: { label: "数值A" }, b: { label: "数值B" } }, options: { mode: { of: "计算A的B%", "what-percent": "计算A占B的百分比", increase: "A增加B%", decrease: "A减少B%" } }, resultLabels: { "A의 B%": "计算结果", "A는 B의": "A占B的百分比", "증가 후 값": "增长后的数值", "감소 후 값": "减少后的数值" }, validation: "请为所选百分比计算输入有效数值。", resultNote: "结果根据所选的百分比公式计算。" },
    discount: { name: "折扣计算器", shortName: "折扣", title: "折扣计算器：折扣金额与最终价格", description: "根据原价和折扣率计算优惠金额与售价，也可以根据原价和售价反算实际折扣率。", howTo: "选择按折扣率计算或按售价反算，并输入所需金额。折扣金额按韩元取整。", formula: "折扣金额 = 原价 × 折扣率 ÷ 100 · 售价 = 原价 − 折扣金额 · 实际折扣率 = (原价 − 售价) ÷ 原价 × 100", example: { question: "原价50,000韩元打八折后是多少？", answer: "优惠10,000韩元，最终价格为40,000韩元。" }, faqs: [{ question: "知道售价后能反算折扣率吗？", answer: "可以。选择根据原价和售价反算即可。" }, { question: "售价可以高于原价吗？", answer: "不可以。高于原价属于涨价，不属于折扣计算。" }], related: ["percentage", "vat", "loan-interest"], fields: { mode: { label: "计算方式" }, price: { label: "原价", unit: "KRW" }, rate: { label: "折扣率", unit: "%" }, sale: { label: "售价", unit: "KRW" } }, options: { mode: { rate: "根据原价和折扣率计算", actual: "根据原价和售价反算" } }, resultLabels: { "할인 금액": "优惠金额", "최종 가격": "最终价格", "실제 할인율": "实际折扣率" }, validation: "原价须为非负数，折扣率须为0%至100%。反算时售价不能高于原价。", resultNote: "折扣金额按韩元取整。" },
    "loan-interest": { name: "贷款还款计算器", shortName: "贷款", title: "贷款还款计算器：月供与总利息", description: "估算等额本息、等额本金和到期一次还本方式的首期还款、利息总额及还款总额。", howTo: "输入贷款本金、年利率和期限，再选择还款方式。期限可用年或月输入。", formula: "等额本息 = P × r ÷ (1 − (1+r)^−n) · 等额本金 = 本金 ÷ 期数 + 剩余本金利息 · 到期还本 = 按月付息，到期偿还本金", example: { question: "12,000,000韩元贷款，年利率0%，12个月还清？", answer: "等额本息方式下每月约还1,000,000韩元，利息为0。" }, faqs: [{ question: "等额本息和等额本金有什么区别？", answer: "等额本息每期还款额基本相同；等额本金每期偿还相同本金，因此初期月供较高。" }, { question: "到期一次还本是什么？", answer: "期限内按月支付利息，到期时一次性偿还本金。" }], related: ["compound-interest", "percentage", "discount"], fields: { principal: { label: "贷款本金", unit: "KRW" }, rate: { label: "年利率", unit: "%" }, months: { label: "贷款期限" }, method: { label: "还款方式" } }, options: { method: { "equal-payment": "等额本息", "equal-principal": "等额本金", bullet: "到期一次还本" } }, resultLabels: { "첫 회차 납입액": "首期还款额", "월 이자 납입액": "每月利息", "만기 상환액": "到期还款额", "총 이자": "利息总额", "총 상환액": "还款总额" }, validation: "本金须大于0，利率须为非负数，期限须为1至1,200个月的整数。", resultNote: "仅供估算。月利息按韩元取整，实际金额会受放款日、费用和利率变化影响。" },
    "compound-interest": { name: "复利计算器", shortName: "复利", title: "复利计算器：按复利频率估算本息", description: "根据本金、年利率、期限和复利频率估算最终金额及利息。", howTo: "输入本金、年利率和期限，并选择利息计入本金的频率。期限可选择年或月。", formula: "最终金额 = 本金 × (1 + 年利率 ÷ 复利次数)^(复利次数 × 年数)", example: { question: "1,000,000韩元按年利率12%、月复利存放一年？", answer: "税前金额约为1,126,825韩元，其中利息约126,825韩元。" }, faqs: [{ question: "复利频率会影响结果吗？", answer: "会。在名义年利率相同的情况下，利息越频繁计入本金，估算金额通常越高。" }, { question: "结果是税后金额吗？", answer: "不是。未计入税费、手续费、利率变化和额外投入。" }], related: ["loan-interest", "percentage", "discount"], fields: { principal: { label: "本金", unit: "KRW" }, rate: { label: "年利率", unit: "%" }, years: { label: "期限" }, frequency: { label: "复利频率" } }, options: { frequency: { "1": "每年1次", "2": "每年2次", "4": "每年4次", "12": "每月复利", "365": "每日复利" } }, resultLabels: { "최종 금액": "最终金额", "총 이자": "利息总额" }, validation: "本金、利率和期限须为非负数，并选择支持的复利频率。", resultNote: "理论税前估算，未计税费、手续费、浮动利率和额外投入。" },
    vat: { name: "增值税计算器", shortName: "增值税", title: "增值税计算器：税额与含税金额", description: "根据未税金额计算增值税和总额，或从含税总额中反算未税金额与税额。", howTo: "选择从未税金额计算或从含税总额反算。按一般10%税率计算，并四舍五入到韩元。", formula: "税额 = 未税金额 × 10% · 总额 = 未税金额 + 税额 · 未税金额 = 含税总额 ÷ 1.1", example: { question: "未税金额10,000韩元的增值税是多少？", answer: "税额为1,000韩元，含税总额为11,000韩元。" }, faqs: [{ question: "如何从含税金额中算出税额？", answer: "将总额除以1.1得到未税金额，再用总额减去未税金额。" }, { question: "所有交易都适用10%吗？", answer: "不一定。免税、零税率和特殊规定可能适用。本工具仅作一般估算。" }], related: ["discount", "percentage", "loan-interest"], fields: { mode: { label: "计算方式" }, amount: { label: "未税金额", unit: "KRW" }, gross: { label: "含税总额", unit: "KRW" } }, options: { mode: { supply: "根据未税金额计算", gross: "根据含税总额反算" } }, resultLabels: { "공급가액": "未税金额", "부가세": "增值税", "합계 금액": "含税总额", "포함된 부가세": "其中税额" }, validation: "请输入非负金额并选择计算方式。", resultNote: "按一般10%增值税计算并取整，不包含具体交易的税务处理。" },
    "date-difference": { name: "日期间隔计算器", shortName: "日期间隔", title: "日期间隔计算器：计算两个日期相差天数", description: "计算开始日期和结束日期之间的天数，并可选择是否计入任一端日期。", howTo: "选择开始日期、结束日期和端点计入规则。结果分别显示实际间隔天数及按选项计算的天数。", formula: "间隔天数 = 结束日期 − 开始日期 · 计入端点天数 = 两日期之间的天数 + 所选端点", example: { question: "1月1日至1月3日相差几天？", answer: "间隔为2天；首尾日期都计入时共3天。" }, faqs: [{ question: "默认会计入开始和结束日期吗？", answer: "实际间隔天数与端点计入规则分开显示，可单独选择。" }, { question: "结束日期可以早于开始日期吗？", answer: "不可以。请将结束日期设为开始日期当天或之后。" }], related: ["age", "percentage", "discount"], fields: { start: { label: "开始日期" }, end: { label: "结束日期" }, include: { label: "计入端点" } }, options: { include: { none: "两端都不计入", start: "计入开始日期", end: "计入结束日期", both: "两端都计入" } }, resultLabels: { "날짜 차이": "间隔天数", "선택한 포함 기준 일수": "按选项计入后的天数" }, validation: "请选择有效日期，并确保结束日期不早于开始日期。", resultNote: "按日历日期计算，不处理具体时刻或夏令时。" },
    age: { name: "周岁计算器", shortName: "周岁", title: "周岁计算器：计算指定日期的年龄", description: "根据出生日期和基准日期计算已满周岁。", howTo: "选择出生日期和计算年龄的基准日期。结果为已满周岁，不使用韩国传统虚岁算法。", formula: "周岁 = 基准年份 − 出生年份 − (基准日期前尚未过今年生日则减1)", example: { question: "2000年12月31日出生的人在2026年12月30日几岁？", answer: "生日的前一天，周岁为25岁。" }, faqs: [{ question: "可以计算过去某一天的年龄吗？", answer: "可以，基准日期须为出生日期当天或之后。" }, { question: "闰年2月29日出生，平年如何计算？", answer: "本计算器将平年的3月1日视为生日。" }], related: ["date-difference", "percentage", "discount"], fields: { birth: { label: "出生日期" }, reference: { label: "基准日期" } }, options: {}, resultLabels: { "만 나이": "周岁" }, validation: "请选择有效日期。基准日期须为出生日期当天或之后。", resultNote: "显示所选基准日期时已满的周岁。" },
    area: { name: "平方米与坪换算器", shortName: "面积换算", title: "面积换算器：平方米与韩国坪单位", description: "在平方米（㎡）和韩国常用面积单位“坪”之间换算。", howTo: "选择换算方向并输入面积。结果最多显示两位小数，并省略多余的末尾零。", formula: "坪 = 平方米 ÷ (400 ÷ 121) · 平方米 = 坪 × (400 ÷ 121) · 1坪 ≈ 3.305785㎡", example: { question: "约33.06㎡是多少坪？", answer: "约10坪。" }, faqs: [{ question: "1坪等于多少平方米？", answer: "本工具按400/121㎡计算，约为3.305785㎡。" }, { question: "为什么换算结果会四舍五入？", answer: "换算系数不是有限小数，因此显示时会按位数取整。" }], related: ["date-difference", "percentage", "vat"], fields: { mode: { label: "换算方向" }, value: { label: "面积" } }, options: { mode: { "sqm-to-pyeong": "平方米换算为坪", "pyeong-to-sqm": "坪换算为平方米" } }, resultLabels: { "평": "坪", "제곱미터": "平方米" }, validation: "请输入非负面积并选择换算方向。", resultNote: "坪是惯用单位；韩国正式房产文件通常使用平方米。" },
  },
};
